In [6]:
%pylab inline
import scipy
import scipy.io.wavfile

Populating the interactive namespace from numpy and matplotlib


In [2]:
def autre(tab, fichier):
    tab1 = tab[0:5]
    tab2 = [[0]] * len(tab1)
    for i in range(len(tab1)):
        tab2[i] = tab1[i][0].tolist()
    fichier.write(str(tab2))
    return tab2     

In [3]:
fichier = open('testautre.txt', 'w')
tab = [array([[0., 0.]]), array([[-5., -4.]]), array([[-433., -413.]]), array([[-451., -439.]]), array([[-552., -532.]])]
print(tab)
a = autre(tab, fichier)
fichier.close()

[array([[0., 0.]]), array([[-5., -4.]]), array([[-433., -413.]]), array([[-451., -439.]]), array([[-552., -532.]])]


In [5]:
print(a)

[[0.0, 0.0], [-5.0, -4.0], [-433.0, -413.0], [-451.0, -439.0], [-552.0, -532.0]]


In [6]:
print(asarray(a))

[[   0.    0.]
 [  -5.   -4.]
 [-433. -413.]
 [-451. -439.]
 [-552. -532.]]


In [7]:
fichierarray = open('tableau.txt', 'r')
t = fichierarray.read()
print(type(t))
fichierarray.close()

<class 'str'>


In [35]:
def autre2(tab):
    tab1 = tab[0:5]
    tab2 = [[0]] * len(tab1)
    for i in range(len(tab1)):
        tab2[i] = tab1[i][0].tolist()
    return tab2

a = autre2(test)
b = asarray(a)
# print(b)

fichier = open('fichieraux.txt', 'w')
contenu = fichier.write(str(b))
fichier.close()

fichier = open('fichieraux.txt', 'r')
contenu = fichier.read()
fichier.close()
print(type(contenu))
print(list(contenu))

<class 'str'>
['[', '[', ' ', ' ', '0', ' ', ' ', ' ', '0', ']', '\n', ' ', '[', ' ', '-', '5', ' ', ' ', '-', '4', ']', '\n', ' ', '[', ' ', '7', '9', ' ', ' ', '9', '9', ']', '\n', ' ', '[', ' ', '6', '1', ' ', ' ', '7', '3', ']', '\n', ' ', '[', '-', '4', '0', ' ', '-', '2', '0', ']', ']']


In [65]:
# IIIIIIIIIIIIIIIIIIIIIIICCCCCCCCCCCCCCCCCCCCCCIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII


test = [array([[0., 0.]]), array([[-5., -4.]]), array([[-433., -413.]]), array([[-451., -439.]]), 
             array([[-552., -532.]])]
print(test)
print(type(test))
test2 = asarray(test)
print()
test2.dump('toto.txt')

a = load('toto.txt')
print(a)
print(type(a))
print(a[0])

[array([[0., 0.]]), array([[-5., -4.]]), array([[-433., -413.]]), array([[-451., -439.]]), array([[-552., -532.]])]
<class 'list'>

[[[   0.    0.]]

 [[  -5.   -4.]]

 [[-433. -413.]]

 [[-451. -439.]]

 [[-552. -532.]]]
<class 'numpy.ndarray'>
[[0. 0.]]


In [29]:
c = asarray(sparse_test)

In [31]:
print(c)

  (1, 0)	-5
  (2, 0)	79
  (3, 0)	61
  (4, 0)	-40
  (1, 1)	-4
  (2, 1)	99
  (3, 1)	73
  (4, 1)	-20


In [55]:
fichier = open('tableautest.txt', 'r')
contenu = fichier.read()
fichier.close()
print(type(contenu))
a = asanyarray(contenu)
print(a)
print(type(a))
print(size(a))
# a = ndarray.dump(asarray(contenu))

<class 'str'>
[array([[0., 0.]]), array([[-5., -4.]]), array([[-433., -413.]]), array([[-451., -439.]]), array([[-552., -532.]])]

<class 'numpy.ndarray'>
1


In [67]:
# IIIIIIIIIIIIIIIIIIIIIIICCCCCCCCCCCCCCCCCCCCCCIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII


test = [array([[0., 0.]]), array([[-5., -4.]]), array([[-433., -413.]]), array([[-451., -439.]]), 
             array([[-552., -532.]])]
print(test)
print(type(test))
test2 = autre2(test)
print("aaaaa ", test2)
ab = asarray(test2)
print(ab)

test2 = asarray(test)
print()
test2.dump('toto.txt')

a = load('toto.txt')
print(a)
print(type(a))
print(a[0])

[array([[0., 0.]]), array([[-5., -4.]]), array([[-433., -413.]]), array([[-451., -439.]]), array([[-552., -532.]])]
<class 'list'>
aaaaa  [[0.0, 0.0], [-5.0, -4.0], [-433.0, -413.0], [-451.0, -439.0], [-552.0, -532.0]]
[[   0.    0.]
 [  -5.   -4.]
 [-433. -413.]
 [-451. -439.]
 [-552. -532.]]

[[[   0.    0.]]

 [[  -5.   -4.]]

 [[-433. -413.]]

 [[-451. -439.]]

 [[-552. -532.]]]
<class 'numpy.ndarray'>
[[0. 0.]]


In [16]:
def liremusique(file):
    freq, data = scipy.io.wavfile.read(file)
    return freq,data

freq, data = liremusique('test.wav')
print(data[3:5])
print(freq)


[[ 0 -1]
 [ 0  0]]
44100


In [47]:
debutechantillon = freq * 30
finechantillon = freq * 60

tableau = data[debutechantillon:finechantillon]

print(finechantillon - debutechantillon)
print(len(tableau))

c = asarray(tableau, dtype = np.int16)


scipy.io.wavfile.write('unbout.wav', freq, c)


print(debutechantillon)
print(finechantillon)

1323000
1323000
1323000
2646000


In [58]:
tab = []
def fourierpartie(data, debut, fin, taillefenetre):
    res = []
    reste = len(data) % taillefenetre
    newtaille = int((len(data) - reste) / taillefenetre)
    for k in range(0, newtaille):
        liste = data[taillefenetre * k:taillefenetre*(k+1)]
        tmp = fft.fft2(liste)
        res = res + [tmp]
    return reste, res
    
def fourierinverse(data):
    tab = fft.ifft2(data)
    tab2 = data
    return tab2

reste, tab = fourierpartie(tableau, debutechantillon, finechantillon, 10)
# print(tab)
print(len(tab))
#tab2 = fourierinverse(tab)
#print(tab2)
#print(len(tab2))

132300


In [65]:
print(type(tab))
# inter = restructuration(tab)
donnees = asarray(tab)

donnees.dump('imag30sec.txt')

<class 'list'>


In [61]:
print(len(tab))

132300


In [44]:
# tab = [1,2,3,4,5,6,7,8,9]

# def fourierpartie(data, debut, fin, taillefenetre):
    res = []
    reste = len(data) % taillefenetre
    print(len(data))
    print(reste)
    newtaille = int((len(data) - reste) / taillefenetre)
    print(newtaille)
    #for k in range(0, newtaille):
       # liste = data[taillefenetre * k:taillefenetre*(k+1)]
        #print(len(liste))
    #return reste, tab
    
#rest, tab = fourierpartie(tableau, debutechantillon, finechantillon, 10)
# fourierpartie(tab, 0, len(tab), 4)
print(tab)
print(len(tab))

9
1
2
[1, 2, 3, 4, 5, 6, 7, 8, 9]
9


In [32]:
c = asarray(tab2, dtype = np.int16)


scipy.io.wavfile.write('unboutreecrit.wav', freq, c)

/usr/local/lib/python3.6/dist-packages/numpy/core/numeric.py:501: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
