In [9]:
%pylab inline
import scipy
import scipy.io.wavfile

Populating the interactive namespace from numpy and matplotlib


In [10]:
def autre(tab, fichier):
    tab1 = tab[0:5]
    tab2 = [[0]] * len(tab1)
    for i in range(len(tab1)):
        tab2[i] = tab1[i][0].tolist()
    fichier.write(str(tab2))
    return tab2     

In [11]:
fichier = open('testautre.txt', 'w')
tab = [array([[0., 0.]]), array([[-5., -4.]]), array([[-433., -413.]]), array([[-451., -439.]]), array([[-552., -532.]])]
print(tab)
a = autre(tab, fichier)
fichier.close()

[array([[0., 0.]]), array([[-5., -4.]]), array([[-433., -413.]]), array([[-451., -439.]]), array([[-552., -532.]])]


In [12]:
print(a)

[[0.0, 0.0], [-5.0, -4.0], [-433.0, -413.0], [-451.0, -439.0], [-552.0, -532.0]]


In [13]:
print(asarray(a))

[[   0.    0.]
 [  -5.   -4.]
 [-433. -413.]
 [-451. -439.]
 [-552. -532.]]


In [14]:
fichierarray = open('tableau.txt', 'r')
t = fichierarray.read()
print(type(t))
fichierarray.close()

<class 'str'>


In [18]:
def autre2(tab):
    print(tab)
    tab1 = tab[0:5]
    tab2 = [[0]] * len(tab1)
    for i in range(len(tab1)):
        tab2[i] = tab1[i][0].tolist()
    return tab2

#a = autre2(test)
#b = asarray(a)
# print(b)

#fichier = open('fichieraux.txt', 'w')
#contenu = fichier.write(str(b))
#fichier.close()

fichier = open('fichieraux.txt', 'r')
contenu = fichier.read()
fichier.close()
print(type(contenu))
print(list(contenu))

<class 'str'>
[]


In [19]:
# IIIIIIIIIIIIIIIIIIIIIIICCCCCCCCCCCCCCCCCCCCCCIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII


test = [array([[0., 0.]]), array([[-5., -4.]]), array([[-433., -413.]]), array([[-451., -439.]]), 
             array([[-552., -532.]])]
print(test)
print(type(test))
test2 = asarray(test)
print()
test2.dump('toto.txt')

a = load('toto.txt')
print(a)
print(type(a))
print(a[0])

[array([[0., 0.]]), array([[-5., -4.]]), array([[-433., -413.]]), array([[-451., -439.]]), array([[-552., -532.]])]
<class 'list'>

[[[   0.    0.]]

 [[  -5.   -4.]]

 [[-433. -413.]]

 [[-451. -439.]]

 [[-552. -532.]]]
<class 'numpy.ndarray'>
[[0. 0.]]


In [21]:
#c = asarray(sparse_test)

In [23]:
#print(c)

In [25]:
#fichier = open('tableautest.txt', 'r')
#contenu = fichier.read()
#fichier.close()
#print(type(contenu))
#a = asanyarray(contenu)
#print(a)
#print(type(a))
#print(size(a))
# a = ndarray.dump(asarray(contenu))

In [26]:
# IIIIIIIIIIIIIIIIIIIIIIICCCCCCCCCCCCCCCCCCCCCCIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII


test = [array([[0., 0.]]), array([[-5., -4.]]), array([[-433., -413.]]), array([[-451., -439.]]), 
             array([[-552., -532.]])]
print(test)
print(type(test))
test2 = autre2(test)
print("aaaaa ", test2)
ab = asarray(test2)
print(ab)

test2 = asarray(test)
print()
test2.dump('toto.txt')

a = load('toto.txt')
print(a)
print(type(a))
print(a[0])

[array([[0., 0.]]), array([[-5., -4.]]), array([[-433., -413.]]), array([[-451., -439.]]), array([[-552., -532.]])]
<class 'list'>
[array([[0., 0.]]), array([[-5., -4.]]), array([[-433., -413.]]), array([[-451., -439.]]), array([[-552., -532.]])]
aaaaa  [[0.0, 0.0], [-5.0, -4.0], [-433.0, -413.0], [-451.0, -439.0], [-552.0, -532.0]]
[[   0.    0.]
 [  -5.   -4.]
 [-433. -413.]
 [-451. -439.]
 [-552. -532.]]

[[[   0.    0.]]

 [[  -5.   -4.]]

 [[-433. -413.]]

 [[-451. -439.]]

 [[-552. -532.]]]
<class 'numpy.ndarray'>
[[0. 0.]]


In [27]:
def liremusique(file):
    freq, data = scipy.io.wavfile.read(file)
    return freq,data

freq, data = liremusique('test.wav')
print(data[3:5])
print(freq)


[[ 0 -1]
 [ 0  0]]
44100


In [28]:
debutechantillon = freq * 30
finechantillon = freq * 60

tableau = data[debutechantillon:finechantillon]

print(finechantillon - debutechantillon)
print(len(tableau))

c = asarray(tableau, dtype = np.int16)


scipy.io.wavfile.write('unbout.wav', freq, c)


print(debutechantillon)
print(finechantillon)

1323000
1323000
1323000
2646000


In [56]:
tab = []
def fourierpartie(data, debut, fin, taillefenetre):
    res = []
    reste = len(data) % taillefenetre
    newtaille = int((len(data) - reste) / taillefenetre)
    for k in range(0, newtaille):
        liste = data[taillefenetre * k:taillefenetre*(k+1)]
        tmp = fft.fft2(liste)
        res = res + [tmp]
    return reste, res
    
    
def fourierinverse(data, debut, fin, taillefenetre):
    res = []
    reste = len(data) % taillefenetre
    newtaille = int((len(data) - reste) / taillefenetre)
    for k in range(0, newtaille):
        liste = data[taillefenetre * k:taillefenetre*(k+1)]
        tmp = fft.ifft2(liste)
        res = res + [tmp]
    return reste, res

reste, tab = fourierpartie(tableau, debutechantillon, finechantillon, 10)
# print(tab)
print(len(tab))
tab2 = fourierinverse(tab, debutechantillon, finechantillon, 10)
#print(tab2)
#print(len(tab2))

132300


In [62]:
print(len(tab))
print(type(tab))
print(type(tab[0]))
print(type(tab[1]))
print(tab[0:5])

132300
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[array([[-7.54100000e+03+0.00000000e+00j,  8.50000000e+01+0.00000000e+00j],
       [-2.90229490e+02-8.43455737e+01j, -2.55572809e+00+1.64782315e+01j],
       [-1.36085639e+03-6.30471318e+02j, -2.63932023e-01-2.54337675e+01j],
       [-3.23770510e+02+8.18381527e+02j, -2.04442719e+01-9.83812666e-01j],
       [-1.51143612e+02+2.69892028e+01j, -4.73606798e+00+9.25329503e+00j],
       [-1.07000000e+02+0.00000000e+00j, -9.00000000e+00+1.33226763e-15j],
       [-1.51143612e+02-2.69892028e+01j, -4.73606798e+00-9.25329503e+00j],
       [-3.23770510e+02-8.18381527e+02j, -2.04442719e+01+9.83812666e-01j],
       [-1.36085639e+03+6.30471318e+02j, -2.63932023e-01+2.54337675e+01j],
       [-2.90229490e+02+8.43455737e+01j, -2.55572809e+00-1.64782315e+01j]]), array([[-3.38900000e+03+0.00000000e+00j,  1.39000000e+02+0.00000000e+00j],
       [ 7.30438427e+02-1.04061188e+03j, -4.17426458e+01+1.17961939e+01j],
       [-1.56208588e+03+1.2

In [68]:
#exe = asarray(tab)
#print(type(exe))
#print(exe[0:5])
def autre(tab):
    tab1 = tab[0:5]
    tab2 = [[0]] * len(tab1)
    for i in range(len(tab1)):
        tab2[i] = tab1[i][0].tolist()
    return tab2 

exe = autre(tab)
print(type(exe))
print(exe[0:5])
exe2 = asarray(exe)
print(type(exe2))
print(exe2[0:5])

<class 'list'>
[[(-7541+0j), (85+0j)], [(-3389+0j), (139+0j)], [(-4225+0j), (-9+0j)], [(-3585+0j), (-23+0j)], [(-2405+0j), (119+0j)]]
<class 'numpy.ndarray'>
[[-7541.+0.j    85.+0.j]
 [-3389.+0.j   139.+0.j]
 [-4225.+0.j    -9.+0.j]
 [-3585.+0.j   -23.+0.j]
 [-2405.+0.j   119.+0.j]]


In [45]:
print(type(tab))
print(len(tab2[1]))
#print(tab2[1])
# inter = restructuration(tab)
donnees = asarray(tab)

donnees.dump('imag30sec.txt')

<class 'list'>
13230


In [38]:
print(len(tab))

132300


In [39]:
# tab = [1,2,3,4,5,6,7,8,9]

# def fourierpartie(data, debut, fin, taillefenetre):
#    res = []
#    reste = len(data) % taillefenetre
#    print(len(data))
#    print(reste)
#    newtaille = int((len(data) - reste) / taillefenetre)
#    print(newtaille)
    #for k in range(0, newtaille):
       # liste = data[taillefenetre * k:taillefenetre*(k+1)]
        #print(len(liste))
    #return reste, tab
    
#rest, tab = fourierpartie(tableau, debutechantillon, finechantillon, 10)
# fourierpartie(tab, 0, len(tab), 4)
#print(tab)
#print(len(tab))

In [34]:
c = asarray(tab2, dtype = np.int16)


scipy.io.wavfile.write('unboutreecrit.wav', freq, c)

NameError: name 'tab2' is not defined

In [54]:
tab = [9, 23, 45, 23, 234, 235]
restab = []
for i in range(0, len(tab), 2):
    print(i)
    restab += [fft.fft(tab[i:i+2])]
print(restab)

print(fft.fft([tab[0]]))

0
2
4
[array([ 32.+0.j, -14.+0.j]), array([68.+0.j, 22.+0.j]), array([469.+0.j,  -1.+0.j])]
[9.+0.j]
