In [2]:
from numpy import *
from scipy import *
from matplotlib import *
import scipy.io.wavfile

In [3]:
freq, data = scipy.io.wavfile.read('test.wav')
print(freq)
print(data)
print(len(data))

44100
[[  0   0]
 [ -1   0]
 [  0   0]
 ...
 [144 163]
 [113 147]
 [ 73  88]]
8833224


In [33]:
print(len(data) // 1104153)
fichier = arg[1]

8


In [30]:
import sys

In [31]:
for arg in sys.argv:
    print(arg)

/usr/local/PYTHON/3.6.5/lib/python3.6/site-packages/ipykernel_launcher.py
-f
/run/user/11491/jupyter/kernel-d939dea0-3f31-44da-8956-dad107b8eb80.json


In [29]:
tab1 = []
tab2 = []
tab3 = []
tab4 = []
tab5 = []
tab6 = []
tab7 = []
tab8 = []
tableau = [tab1, tab2, tab3, tab4, tab5, tab6, tab7, tab8]

    
step = int(len(data) / 8)
print(step)

def parrallelisation(nomfichier, debut, fin, data):
    tab1 = []

# fichier = arg[1]
    
def fourierparpartie(data, debut, fin, taillefenetre):
    res = []
    reste = len(data) % taillefenetre
    newtaille = int((len(data) - reste) / taillefenetre)
    for k in range(0, newtaille):
        liste = data[taillefenetre * k:taillefenetre*(k+1)]
        tmp = fft.fft2(liste)
        res = res + [tmp]
    return reste, res
    
def fourierinverse(data):
    tab = fft.ifft2(data)
    tab2 = data
    return tab2

reste, tab = fourierpartie(tableau, debutechantillon, finechantillon, 10)
    
# for i in range(0, step):
    
    

print(tableau[6])

1104153
[6]


In [34]:
freq, data = scipy.io.wavfile.read('test.wav')
print(freq)
print(data)
print(len(data))

44100
[[  0   0]
 [ -1   0]
 [  0   0]
 ...
 [144 163]
 [113 147]
 [ 73  88]]
8833224


In [36]:
print(len(data) // 8)

1104153


In [38]:
print(1104153 * 8)
print(8833232)

8833224
8833232


In [76]:
m1 = load('mrc1.txt')

In [77]:
print(type(m1))
print(m1[0:50])

<class 'numpy.ndarray'>
[   0   -1    0    0    0    0    0    0    0    0   -5    7  -17   30
  -88 -347 -384 -407 -386 -418 -433 -409 -356 -329 -404 -462 -410 -424
 -432 -422 -451 -450 -486 -514 -503 -438 -440 -504 -524 -542 -552 -558
 -514 -468 -443 -384 -328 -315 -266 -208]


In [46]:
print(data)
res = []

[[  0   0]
 [ -1   0]
 [  0   0]
 ...
 [144 163]
 [113 147]
 [ 73  88]]


In [47]:
reste = len(data) % 10
newtaille = int((len(data) - reste) / 10)
print(reste, newtaille)

4 883322


In [49]:
liste = data[10 * 0:10*(0+1)]
tmp = numpy.fft.fft2(liste)
res = res + [tmp]
print(res)

[array([[-2.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [-5.00000000e-01+1.53884177e+00j, -1.11803399e+00-3.63271264e-01j],
       [ 5.00000000e-01+3.63271264e-01j, -1.11803399e+00+1.53884177e+00j],
       [-5.00000000e-01+3.63271264e-01j,  1.11803399e+00+1.53884177e+00j],
       [ 5.00000000e-01+1.53884177e+00j,  1.11803399e+00-3.63271264e-01j],
       [ 2.00000000e+00-1.44328993e-15j, -6.66133815e-16+1.11022302e-15j],
       [ 5.00000000e-01-1.53884177e+00j,  1.11803399e+00+3.63271264e-01j],
       [-5.00000000e-01-3.63271264e-01j,  1.11803399e+00-1.53884177e+00j],
       [ 5.00000000e-01-3.63271264e-01j, -1.11803399e+00-1.53884177e+00j],
       [-5.00000000e-01-1.53884177e+00j, -1.11803399e+00+3.63271264e-01j]]), array([[-2.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [-5.00000000e-01+1.53884177e+00j, -1.11803399e+00-3.63271264e-01j],
       [ 5.00000000e-01+3.63271264e-01j, -1.11803399e+00+1.53884177e+00j],
       [-5.00000000e-0

In [52]:
liste = data[(len(data) - reste): len(data)]
print(liste)
res = res + [numpy.fft.fft2(liste)]
print(res)

[[129 149]
 [144 163]
 [113 147]
 [ 73  88]]
[array([[-2.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [-5.00000000e-01+1.53884177e+00j, -1.11803399e+00-3.63271264e-01j],
       [ 5.00000000e-01+3.63271264e-01j, -1.11803399e+00+1.53884177e+00j],
       [-5.00000000e-01+3.63271264e-01j,  1.11803399e+00+1.53884177e+00j],
       [ 5.00000000e-01+1.53884177e+00j,  1.11803399e+00-3.63271264e-01j],
       [ 2.00000000e+00-1.44328993e-15j, -6.66133815e-16+1.11022302e-15j],
       [ 5.00000000e-01-1.53884177e+00j,  1.11803399e+00+3.63271264e-01j],
       [-5.00000000e-01-3.63271264e-01j,  1.11803399e+00-1.53884177e+00j],
       [ 5.00000000e-01-3.63271264e-01j, -1.11803399e+00-1.53884177e+00j],
       [-5.00000000e-01-1.53884177e+00j, -1.11803399e+00+3.63271264e-01j]]), array([[-2.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [-5.00000000e-01+1.53884177e+00j, -1.11803399e+00-3.63271264e-01j],
       [ 5.00000000e-01+3.63271264e-01j, -1.11803399

In [69]:
def fourierparpartie(data, debut, fin, taillefenetre):
    print("Debut fourier ..................")
    res = []
    reste = len(data) % taillefenetre
#     newtaille = int((len(data) - reste) / taillefenetre)
    for k in range(0, (fin-debut-1)):
        liste = data[taillefenetre * k:taillefenetre*(k+1)]
        tmp = numpy.fft.fft2(liste)
        res = res + [tmp]
    liste = data[(len(data) - reste): len(data)]
    res = res + [numpy.fft.fft2(liste)]
    return res

a = fourierparpartie(data, 0, 15, 10)

Debut fourier ..................


In [70]:
print(a)

[array([[-2.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [-5.00000000e-01+1.53884177e+00j, -1.11803399e+00-3.63271264e-01j],
       [ 5.00000000e-01+3.63271264e-01j, -1.11803399e+00+1.53884177e+00j],
       [-5.00000000e-01+3.63271264e-01j,  1.11803399e+00+1.53884177e+00j],
       [ 5.00000000e-01+1.53884177e+00j,  1.11803399e+00-3.63271264e-01j],
       [ 2.00000000e+00-1.44328993e-15j, -6.66133815e-16+1.11022302e-15j],
       [ 5.00000000e-01-1.53884177e+00j,  1.11803399e+00+3.63271264e-01j],
       [-5.00000000e-01-3.63271264e-01j,  1.11803399e+00-1.53884177e+00j],
       [ 5.00000000e-01-3.63271264e-01j, -1.11803399e+00-1.53884177e+00j],
       [-5.00000000e-01-1.53884177e+00j, -1.11803399e+00+3.63271264e-01j]]), array([[-3961.        +0.00000000e+00j,   -69.        +0.00000000e+00j],
       [  771.09268244-2.33109574e+03j,    -4.46149284-4.95936961e+01j],
       [  -19.79933357-1.40587805e+02j,    32.14183272-2.48459823e+01j],
       [  660.40731756-4.585

In [81]:
print(a[0:15])

[array([[-2.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [-5.00000000e-01+1.53884177e+00j, -1.11803399e+00-3.63271264e-01j],
       [ 5.00000000e-01+3.63271264e-01j, -1.11803399e+00+1.53884177e+00j],
       [-5.00000000e-01+3.63271264e-01j,  1.11803399e+00+1.53884177e+00j],
       [ 5.00000000e-01+1.53884177e+00j,  1.11803399e+00-3.63271264e-01j],
       [ 2.00000000e+00-1.44328993e-15j, -6.66133815e-16+1.11022302e-15j],
       [ 5.00000000e-01-1.53884177e+00j,  1.11803399e+00+3.63271264e-01j],
       [-5.00000000e-01-3.63271264e-01j,  1.11803399e+00-1.53884177e+00j],
       [ 5.00000000e-01-3.63271264e-01j, -1.11803399e+00-1.53884177e+00j],
       [-5.00000000e-01-1.53884177e+00j, -1.11803399e+00+3.63271264e-01j]]), array([[-3961.        +0.00000000e+00j,   -69.        +0.00000000e+00j],
       [  771.09268244-2.33109574e+03j,    -4.46149284-4.95936961e+01j],
       [  -19.79933357-1.40587805e+02j,    32.14183272-2.48459823e+01j],
       [  660.40731756-4.585

In [68]:
def conversionpropre(tab):
    print("Debut conversion ..................")
    tab2 = [[0]] * len(tab)
    for i in range(len(tab)):
        tab2[i] = tab[i][0].tolist()
    tab2 = asarray(tab2)
    return tab2

b = conversionpropre(a)
print(b)

Debut conversion ..................
[[-2.000e+00+0.j  0.000e+00+0.j]
 [-3.961e+03+0.j -6.900e+01+0.j]
 [-8.038e+03+0.j -1.240e+02+0.j]
 [-9.631e+03+0.j -7.300e+01+0.j]
 [-7.989e+03+0.j -8.300e+01+0.j]
 [-1.892e+03+0.j -4.800e+01+0.j]
 [-6.320e+02+0.j -6.800e+01+0.j]
 [ 2.730e+03+0.j  0.000e+00+0.j]
 [ 1.368e+03+0.j -8.800e+01+0.j]
 [-6.420e+02+0.j -7.800e+01+0.j]
 [-2.738e+03+0.j -9.800e+01+0.j]
 [-5.837e+03+0.j -1.230e+02+0.j]
 [-5.072e+03+0.j -1.680e+02+0.j]
 [ 7.190e+02+0.j  1.500e+01+0.j]
 [ 3.066e+03+0.j  2.000e+01+0.j]
 [ 1.006e+03+0.j -8.800e+01+0.j]]


In [72]:
b.dump('toto.txt')

In [73]:
c = load('toto.txt')

In [74]:
print(c)

[[-2.000e+00+0.j  0.000e+00+0.j]
 [-3.961e+03+0.j -6.900e+01+0.j]
 [-8.038e+03+0.j -1.240e+02+0.j]
 [-9.631e+03+0.j -7.300e+01+0.j]
 [-7.989e+03+0.j -8.300e+01+0.j]
 [-1.892e+03+0.j -4.800e+01+0.j]
 [-6.320e+02+0.j -6.800e+01+0.j]
 [ 2.730e+03+0.j  0.000e+00+0.j]
 [ 1.368e+03+0.j -8.800e+01+0.j]
 [-6.420e+02+0.j -7.800e+01+0.j]
 [-2.738e+03+0.j -9.800e+01+0.j]
 [-5.837e+03+0.j -1.230e+02+0.j]
 [-5.072e+03+0.j -1.680e+02+0.j]
 [ 7.190e+02+0.j  1.500e+01+0.j]
 [ 3.066e+03+0.j  2.000e+01+0.j]
 [ 1.006e+03+0.j -8.800e+01+0.j]]


In [79]:
print(len(data) % 8)

0
